name: Deploy VOSOX Frontend

on:
  push:
    branches: [ integration ]

jobs:
  deploy:
    runs-on: [self-hosted, dev]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t vosox-frontend .

      - name: Stop existing container if running
        run: docker stop vosox-frontend-container || true

      - name: Remove existing container if exists
        run: docker rm vosox-frontend-container || true

      - name: Run Docker container
        run: docker run -d --name vosox-frontend-container -p 5015:5015 -p 5016:5016 -p 5017:5017 -p 5018:5018 vosox-frontend
